### ISSUE TITLE
Add GitHub issue forms

### ISSUE THREAD

**Issue by Hard-Coder05** [camunda-community-hub/eze#37]
__Is your feature request related to a problem? Please describe.__

GitHub has recently rolled out a [public beta for their issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) feature. This would allow you to create interactive issue templates and validate them 🤯.

__Describe the solution you'd like__

This repository currently uses no issue template. Your task is to create GitHub issue forms for this repository. We can use this standard issue templates as a reference for this PR.

**Comment by Hard-Coder05** [comment]
@saig0 I would like to work on this issue!

**Comment by ieshreya** [comment]
If this issue is still open, I'd like to work on it. Thanks :)

**Comment by saig0** [comment]
@Hard-Coder05 thank you for raising this up.

I'm not sure about it yet. I need to check if it can offer value for this project. 

---

Please note that I would **not** consider this for the **Hacktoberfest** since it doesn't add much value to the project (i.e. the codebase). Look at [these issues](https://github.com/camunda-community-hub/eze/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest) if you want to contribute for the Hacktoberfest.

**Comment by Zelldon** [comment]
Same for me, see similar comment here https://github.com/camunda-community-hub/zeebe-client-csharp/issues/326#issuecomment-933202151

**Comment by Hard-Coder05** [comment]
@saig0 okay I would llook into some other issues then!
